module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['index', 'intro/story', 'intro/cdn', 'intro/next',],
    },
    {
      type: 'category',
      label: 'Javascript',
      collapsed: false,
      items: ['vanilla/overview',],
    },
    {
      type: 'category',
      label: 'Angular',
      collapsed: false,
      items: ['angular/overview',],
    },
    {
      type: 'category',
      label: 'React',
      collapsed: false,
      items: ['react/overview',],
    },
    {
      type: 'category',
      label: 'Vue',
      collapsed: false,
      items: ['vue/overview',],
    },
    {
      type: 'category',
      label: 'Configure',
      collapsed: false,
      items: ['configure/overview',],
    },
  ],

  api: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['components',],
    },
    {
      type: 'category',
      label: 'Components',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api', // Generate section automatically based on files
        },
      ],
    },
  ],

  cli: [
    {
      type: 'category',
      label: 'CLI Documentation',
      collapsed: false,
      items: ['cli',],
    },
  ],

  addons: [
    {
      type: 'category',
      label: 'Addons Documentation',
      collapsed: false,
      items: ['addons',],
    },
    
  ]
}